### ISSUE TITLE
performance and caching

### ISSUE THREAD

**Issue by icylace** [golavender/lavender#92]
I started trying out Lavender in a Laravel project I'm working on right now.  I'm finding that Lavender is noticeably slower than Laravel's Blade which is not surprising but it would be great if there were ways to optimize for performance.

Is there a way to precompile Lavender into plain PHP?  This would allow us to develop in Lavender but use plain PHP views in production.  It seems the only compilation option available is to compile all the way into the final HTML output.

**Comment by sudo-reboot** [comment]
view caching is a thing now https://github.com/golavender/lavender/releases/tag/v0.20.0. still has to compile the views every page load obviously but no longer has to re-parse the view files every time. 

at this point my applications are spending more time in the composer autoloader than compiling views so i'm going to close this, if anyone still has trouble with performance definitely let me know
